name: "E2E tests scheduling"

on:
  schedule:
    - cron: "0 9-21/2 * * 1-5" # Every 2 hours from 9 AM to 9 PM, Monday to Friday
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  e2e:
    uses: kestra-io/actions/.github/workflows/kestra-oss-e2e-tests.yml@main
    with:
      java-version: 25
